language: node_js

node_js:
  - "8"

script:
  - echo "npm test disabled"

before_deploy: "npm run build"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
